# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_cat',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
