# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-19 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_cat_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product_list',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='tutorial_comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='upcoming_product',
            name='cat',
        ),
        migrations.DeleteModel(
            name='User_Info',
        ),
        migrations.DeleteModel(
            name='Product_Cat',
        ),
        migrations.DeleteModel(
            name='Product_Comment',
        ),
        migrations.DeleteModel(
            name='Product_List',
        ),
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.DeleteModel(
            name='Tutorial_Cat',
        ),
        migrations.DeleteModel(
            name='Tutorial_Comment',
        ),
        migrations.DeleteModel(
            name='Upcoming_Product',
        ),
    ]
