# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20171019_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_cat',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
