# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20171021_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_list',
            name='img',
        ),
        migrations.AddField(
            model_name='product_list',
            name='image',
            field=models.ImageField(blank=True, upload_to='catagory'),
        ),
    ]
